name: 🏷️ JIRA ID Validator

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    # No branch filtering - will run on all PRs

jobs:
  jira-pr-check:
    name: 🏷️ Validate JIRA ticket ID
    # Use the reusable workflow from the central repository
    uses: marklogic/pr-workflows/.github/workflows/jira-id-check.yml@main