name: Copyright Validation

on:
  workflow_call:

jobs:
  copyright-check:
    name: Validate Copyright Headers
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout PR head (target repository code)
      uses: actions/checkout@v4
      with:
        # Checkout the PR head - this gets the target repo code with changes
        ref: ${{ github.event.pull_request.head.sha }}
        path: target-repo
    
    - name: Checkout pr-workflows repository (for validation script)
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository_owner }}/pr-workflows
        ref: copyright
        path: pr-workflows
    
    - name: Setup copyright configuration
      id: setup-config
      run: |
        echo "Setting up copyright configuration..."
        
        config_file="target-repo/.copyrightconfig"
        config_source="PR head"
        
        # Check if config file exists in PR head
        if [ ! -f "$config_file" ]; then
          echo "Config file not in PR head, checking base branch..."
          
          # Checkout base repository to get config file
          # Use GITHUB_TOKEN for authentication (works for both public and private repos)
          git clone --depth 1 --branch ${{ github.event.pull_request.base.ref }} \
            https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git base-repo
          
          base_config_file="base-repo/.copyrightconfig"
          
          if [ -f "$base_config_file" ]; then
            echo "Using config from base repository"
            config_file="$base_config_file"
            config_source="base repository"
          else
            echo "Error: .copyrightconfig not found" && exit 1
          fi
        else
          echo "Using config from PR head"
        fi
        
        # Validate config file content
        if [ ! -s "$config_file" ]; then
          echo "Error: empty config" && exit 1
        fi
        
        # Check for required startyear
        if ! grep -q "^startyear:" "$config_file"; then
          echo "Error: startyear missing" && exit 1
        fi
        
        echo "✅ Using copyright configuration from $config_source"
        echo "Configuration content:"
        echo "========================"
        cat "$config_file"
        echo "========================"
        
        # Export config file path for later steps
        echo "config-file=$config_file" >> $GITHUB_OUTPUT
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Get changed files
      id: changed-files
      run: |
        echo "Getting list of changed files..."
        
        cd target-repo
        
        # Get the base and head refs for comparison
        base_sha="${{ github.event.pull_request.base.sha }}"
        head_sha="${{ github.event.pull_request.head.sha }}"
        
        echo "Getting changes introduced by the PR..."
        echo "Base SHA: $base_sha"
        echo "Head SHA: $head_sha"
        
        # Fetch the base branch to compare against
        git fetch origin ${{ github.event.pull_request.base.ref }}
        
        # Get files changed between base and PR head
        changed_files=$(git diff --name-only --diff-filter=AMR "$base_sha" "$head_sha")
        
        if [ -z "$changed_files" ]; then
            echo "No files changed in this PR"
            echo "files-count=0" >> $GITHUB_OUTPUT
            echo "skip-validation=true" >> $GITHUB_OUTPUT
            exit 0
        fi
        
        echo "Files changed by PR:"
        echo "$changed_files"
        
        # Filter existing files and create list for validation
        echo "$changed_files" | xargs -I {} sh -c '[ -f "{}" ] && echo "{}"' > ../files_to_check.txt
        existing_count=$(cat ../files_to_check.txt | wc -l | tr -d ' ')
        
        if [ "$existing_count" -eq 0 ]; then
          echo "No existing files to validate (all files were deleted)"
          echo "files-count=0" >> $GITHUB_OUTPUT
          echo "skip-validation=true" >> $GITHUB_OUTPUT
        else
          echo "Files to validate: $existing_count"
          # Save file list for next step (as relative paths without prefixes)
          echo "$changed_files" | xargs -I {} sh -c '[ -f "{}" ] && echo "{}"' > ../files_to_check.txt
          echo "files-count=$existing_count" >> $GITHUB_OUTPUT
          echo "skip-validation=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Validate
      id: validate
      if: steps.changed-files.outputs.skip-validation != 'true'
      run: |
        set -o pipefail
        echo "Starting copyright validation..."
        
        # Debug: List current directory contents
        echo "Current directory contents:"
        ls -la
        
        # Debug: Check pr-workflows directory structure
        echo "pr-workflows directory contents:"
        ls -la pr-workflows/
        if [ -d "pr-workflows/scripts" ]; then
          echo "pr-workflows/scripts directory contents:"
          ls -la pr-workflows/scripts/
        else
          echo "❌ pr-workflows/scripts directory does not exist"
        fi
        
        script_path="pr-workflows/scripts/copyrightcheck.py"
        config_file="${{ steps.setup-config.outputs.config-file }}"
        
        # Verify copyright script exists in pr-workflows repo
        if [ ! -f "$script_path" ]; then
          echo "❌ Error: $script_path not found in pr-workflows repository"
          echo "Please ensure the copyright check script exists in the pr-workflows repository"
          exit 1
        fi
        
        # Make script executable
        chmod +x "$script_path"
        
        # Read files to check
        if [ ! -f "files_to_check.txt" ]; then
          echo "❌ Error: No files to check"
          exit 1
        fi
        
        files_to_check=$(tr '\n' ' ' < files_to_check.txt)
        echo "Validating files: $files_to_check"
        
        # Run validation (script always verbose now)
        echo "Running copyright validation..."
        echo "🔧 Command: python3 $script_path --config $config_file --working-dir target-repo $files_to_check"
        
        if python3 "$script_path" --config "$config_file" --working-dir target-repo $files_to_check > validation_output.txt 2>&1; then
          echo "✅ Copyright validation passed"
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "❌ Copyright validation failed"
          echo "status=failed" >> $GITHUB_OUTPUT
          exit 1
        fi
    
    - name: Detailed Summary
      if: steps.changed-files.outputs.skip-validation != 'true'
      run: |
        python3 - <<'PY'
import re, os
summary_file = os.environ.get('GITHUB_STEP_SUMMARY')
out_path = 'validation_output.txt'
if not os.path.exists(out_path):
    with open(summary_file,'a') as s: s.write("No validation output captured.\n")
    raise SystemExit(0)
with open(out_path,'r') as f:
    lines = f.read().splitlines()
counts={'total':0,'valid':0,'invalid':0,'excluded':0}
for line in lines:
    t=line.strip()
    for key,label in [('Total files checked','total'),('Valid files','valid'),('Invalid files','invalid'),('Excluded files','excluded')]:
        if t.startswith(key+':'):
            try: counts[label]=int(t.split(':',1)[1].strip())
            except: pass
# Collect sections
def collect_after(header):
    res=[]; active=False
    for l in lines:
        s=l.strip()
        if s==header:
            active=True; continue
        if active:
            if not s: break
            if s.endswith(':') and s in ('Excluded files:','Valid files:'): break
            if '/' in s:
                path=s[s.index('/'):]  # from first slash
                res.append(path.strip())
    return res
excluded = collect_after('Excluded files:')
valid_sec = collect_after('Valid files:')
# Invalid blocks
invalid=[]
i=0
n=len(lines)
while i<n:
    s=lines[i].strip()
    if '/' in s and not any(s.startswith(h) for h in ('Total files checked','Valid files:','Invalid files:','Excluded files:')) and 'Validation Results' not in s:
        path = s[s.index('/'):] if '/' in s else None
        found=expected=error=None
        j=i+1
        while j<n:
            t=lines[j].strip()
            if not t: break
            if t.startswith('Found:'): found=t.split('Found:',1)[1].strip()
            elif t.startswith('Expected:'): expected=t.split('Expected:',1)[1].strip()
            elif t.startswith('Error:'): error=t.split('Error:',1)[1].strip()
            elif '/' in t and t.split('/',1)[0].strip()=='' and expected: break
            j+=1
        if path and expected:
            invalid.append({'file':path,'found':found,'expected':expected,'error':error})
            i=j; continue
    i+=1
# Deduplicate
seen=set(); uniq=[]
for item in invalid:
    if item['file'] not in seen:
        uniq.append(item); seen.add(item['file'])
invalid=uniq
success = counts.get('invalid',0)==0
header = '## ✅ Copyright Validation Passed' if success else '## ❌ Copyright Validation Failed'
parts=[f"Total: {counts['total']}", f"Passed: {counts['valid']}", f"Failed: {counts['invalid']}"]
if counts.get('excluded'): parts.append(f"Skipped: {counts['excluded']}")
md=[header,' | '.join(parts),'']
if invalid:
    md.append('### Failed Files')
    for f in invalid:
        md.append(f"❌ `{f['file']}`")
        if f.get('found'): md.append(f"   Found: {f['found']}")
        if f.get('expected'): md.append(f"   Expected: {f['expected']}")
        if f.get('error'): md.append(f"   Error: {f['error']}")
        md.append('')
if excluded:
    md.append('### Skipped Files')
    for f in excluded: md.append(f"⏭️ `{f}`")
    md.append('')
if valid_sec:
    md.append('### Passed Files')
    for f in valid_sec: md.append(f"✅ `{f}`")
    md.append('')
if not success:
    md.append('### Fix Guidance')
    md.append('Update headers to match Expected line above; then push changes.')
with open(summary_file,'a') as s:
    s.write('\n'.join(md)+'\n')
PY
    
    - name: Summary
      if: always()
      run: |
        if [ "${{ steps.changed-files.outputs.skip-validation }}" = "true" ]; then
          echo "::notice title=Copyright Check::No files to validate"
        elif [ "${{ steps.validate.outputs.status }}" = "success" ]; then
          echo "::notice title=Copyright Check Passed::All files valid"
        else
          echo "::error title=Copyright Check Failed::Some files invalid"; exit 1
        fi
